spring:
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
    initialization-mode: always
    schema:
      - classpath:schema.sql
