spring:
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password: ""
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
    schema:
      - classpath:schema.sql
server:
  servlet:
    session:
      tracking-modes: cookie
logging:
  level:
    com.zaxxer.hikari.pool.HikariPool: debug
    org:
      springframework:
        jdbc:
          core: TRACE
