spring:
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cafe
    username: yeon
    password: yeonise1109
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: always
    schema:
      - classpath:schema.sql
server:
  servlet:
    session:
      tracking-modes: cookie
logging:
  level:
    com.zaxxer.hikari.pool.HikariPool: debug
    org:
      springframework:
        jdbc:
          core: TRACE
