spring:
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cafe
    username: yeon
    password: yeonise1109
  sql:
    init:
      mode: always
    schema:
      - classpath:schema.sql
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  servlet:
    session:
      tracking-modes: cookie
