DROP TABLE IF EXISTS USER;
CREATE TABLE USER
(
    index bigint generated by default as identity, -- INT AUTO_INCREMENT  PRIMARY KEY
    userID  VARCHAR(255) NOT NULL,
    email    VARCHAR(255),
    nickname   VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    signUpDate  VARCHAR(255),
    PRIMARY KEY (index)
);
