CREATE TABLE IF NOT EXISTS USER_INFO
(
    index      bigint       generated by default as identity,
    userID     VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    nickname   VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    signUpDate DATE         NOT NULL,
    PRIMARY KEY (index)
);

CREATE TABLE IF NOT EXISTS WRITE_INFO
(
    index     bigint       generated by default as identity,
    title     VARCHAR(255) NOT NULL,
    writer    VARCHAR(255) NOT NULL,
    contents  VARCHAR(255) NOT NULL,
    writeDate TIMESTAMP(0) NOT NULL,
    hits      bigint       NOT NULL,
    PRIMARY KEY (index)
);
