CREATE TABLE IF NOT EXISTS USER_INFO
(
    index bigint generated by default as identity,
    userID  VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL,
    nickname   VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    signUpDate  DATE NOT NULL,
    PRIMARY KEY (index)
);
