CREATE TABLE USERS(
    IDX INT AUTO_INCREMENT,
    ID VARCHAR(255),
    PASSWORD VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PRIMARY KEY (IDX)
)


CREATE TABLE ARTICLES(
    IDX INT AUTO_INCREMENT,
    ID VARCHAR(255),
    WRITER VARCHAR(255) NOT NULL,
    TITLE VARCHAR(255) NOT NULL ,
    CONTENTS VARCHAR(1000) NOT NULL,
    DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(0)  NOT NULL,
    PRIMARY KEY (IDX)
)